name: Deploy to VPS

on:
  push:
    branches:
      - main  # или другая ветка для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            source ~/.bashrc
            export PATH=/root/.nvm/versions/node/v22.18.0/bin:$PATH
            cd ~/nsd-courses-bot/
            git pull
            /root/.nvm/versions/node/v22.18.0/bin/pnpm install 
            /root/.nvm/versions/node/v22.18.0/bin/pnpm build
            /root/.nvm/versions/node/v22.18.0/bin/pm2 restart bot

